// apps/landing/components/Header.tsx
'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import { Menu, X } from 'lucide-react';
import { Logo } from '@workly/shared-ui';

const navigation = [
  { name: 'Anasayfa', href: '#' },
  { 
    name: 'Özellikler', 
    href: '#features',
  },
  { 
    name: 'Modüller', 
    href: '#modules',
  },
  { name: 'Referanslar', href: '#testimonials' },
  { name: 'İletişim', href: '#footer' },
];

export default function Header() {
  const [isScrolled, setIsScrolled] = useState(false);
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);

  useEffect(() => {
    const handleScroll = () => {
      setIsScrolled(window.scrollY > 10);
    };

    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  return (
    <header
      className={`fixed top-0 left-0 right-0 z-50 transition-all duration-300 bg-white ${
        isScrolled ? 'shadow-lg' : 'shadow-md'
      }`}
    >
      <nav className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex justify-between items-center h-20">
          {/* Logo */}
          <Logo size="md" showText={true} href="/" />

          {/* Desktop Navigation */}
          <div className="hidden lg:flex items-center gap-8">
            {navigation.map((item) => (
              <a
                key={item.name}
                href={item.href}
                className="text-sm font-medium text-gray-700 hover:text-primary-600 transition-colors"
              >
                {item.name}
              </a>
            ))}
          </div>

          {/* CTA Buttons */}
          <div className="hidden lg:flex items-center gap-4">
            <Link
              href="http://localhost:3001"
              className="text-sm font-medium text-gray-700 hover:text-primary-600 transition-colors"
            >
              Giriş Yap
            </Link>
            <Link
              href="http://localhost:3001"
              className="px-6 py-2.5 bg-gradient-to-r from-primary-600 to-secondary-600 text-white font-semibold rounded-lg hover:shadow-lg transition-all transform hover:-translate-y-0.5"
            >
              Ücretsiz Başla
            </Link>
          </div>

          {/* Mobile Menu Button */}
          <button
            onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
            className="lg:hidden p-2 rounded-lg text-gray-700 hover:bg-gray-100 transition-colors"
            aria-label="Toggle menu"
          >
            {isMobileMenuOpen ? (
              <X className="w-6 h-6" />
            ) : (
              <Menu className="w-6 h-6" />
            )}
          </button>
        </div>

        {/* Mobile Menu */}
        <div
          className={`lg:hidden overflow-hidden transition-all duration-300 ${
            isMobileMenuOpen ? 'max-h-96 opacity-100' : 'max-h-0 opacity-0'
          }`}
        >
          <div className="py-4 space-y-2 bg-white/95 backdrop-blur-lg rounded-b-2xl shadow-lg -mx-4 px-4">
            {navigation.map((item) => (
              <a
                key={item.name}
                href={item.href}
                className="block px-4 py-3 text-gray-700 hover:bg-primary-50 hover:text-primary-600 rounded-lg font-medium transition-colors"
                onClick={() => setIsMobileMenuOpen(false)}
              >
                {item.name}
              </a>
            ))}
            <div className="pt-4 border-t border-gray-200 space-y-2">
              <Link
                href="http://localhost:3001"
                className="block px-4 py-3 text-center text-gray-700 hover:bg-gray-100 rounded-lg font-medium transition-colors"
                onClick={() => setIsMobileMenuOpen(false)}
              >
                Giriş Yap
              </Link>
              <Link
                href="http://localhost:3001"
                className="block px-4 py-3 text-center bg-gradient-to-r from-primary-600 to-secondary-600 text-white font-semibold rounded-lg hover:shadow-lg transition-all"
                onClick={() => setIsMobileMenuOpen(false)}
              >
                Ücretsiz Başla
              </Link>
            </div>
          </div>
        </div>
      </nav>
    </header>
  );
}

// apps/hr-management/src/app/components/header/header.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { LogoComponent } from '../logo/logo.component';

interface NavItem {
  name: string;
  path: string;
}

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [CommonModule, RouterLink, RouterLinkActive, LogoComponent],
  template: `
    <header class="bg-white shadow-md border-b border-gray-200 sticky top-0 z-50">
      <nav class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between items-center h-20">
          <!-- Logo -->
          <app-logo [size]="'md'" [showText]="true"></app-logo>

          <!-- Desktop Navigation -->
          <div class="hidden md:flex items-center gap-8">
            <a
              *ngFor="let item of navigation"
              [routerLink]="item.path"
              routerLinkActive="text-teal-600 font-semibold"
              [routerLinkActiveOptions]="{ exact: item.path === '/' }"
              class="text-sm font-medium text-gray-700 hover:text-teal-600 transition-colors"
            >
              {{ item.name }}
            </a>
          </div>

          <!-- CTA Buttons -->
          <div class="hidden md:flex items-center gap-4">
            <a
              href="http://localhost:3000"
              class="text-sm font-medium text-gray-700 hover:text-teal-600 transition-colors"
            >
              Ana Sayfa
            </a>
            <a
              href="http://localhost:3001"
              class="px-6 py-2.5 bg-gradient-to-r from-teal-600 to-green-600 text-white font-semibold rounded-lg hover:shadow-lg transition-all transform hover:-translate-y-0.5"
            >
              Giriş Yap
            </a>
          </div>

          <!-- Mobile Menu Button -->
          <button
            (click)="toggleMobileMenu()"
            class="md:hidden p-2 rounded-lg text-gray-700 hover:bg-gray-100 transition-colors"
            aria-label="Toggle menu"
          >
            <svg
              *ngIf="!isMobileMenuOpen"
              class="w-6 h-6"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M4 6h16M4 12h16M4 18h16"
              />
            </svg>
            <svg
              *ngIf="isMobileMenuOpen"
              class="w-6 h-6"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M6 18L18 6M6 6l12 12"
              />
            </svg>
          </button>
        </div>

        <!-- Mobile Menu -->
        <div
          *ngIf="isMobileMenuOpen"
          class="md:hidden py-4 space-y-2 bg-white/95 backdrop-blur-lg rounded-b-2xl shadow-lg -mx-4 px-4"
        >
            <a
              *ngFor="let item of navigation"
              [routerLink]="item.path"
              routerLinkActive="bg-teal-50 text-teal-600"
              [routerLinkActiveOptions]="{ exact: item.path === '/' }"
              (click)="toggleMobileMenu()"
              class="block px-4 py-3 text-gray-700 hover:bg-teal-50 hover:text-teal-600 rounded-lg font-medium transition-colors"
            >
              {{ item.name }}
            </a>
          <div class="pt-4 border-t border-gray-200 space-y-2">
            <a
              href="http://localhost:3000"
              class="block px-4 py-3 text-center text-gray-700 hover:bg-gray-100 rounded-lg font-medium transition-colors"
            >
              Ana Sayfa
            </a>
            <a
              href="http://localhost:3001"
              class="block px-4 py-3 text-center bg-gradient-to-r from-teal-600 to-green-600 text-white font-semibold rounded-lg hover:shadow-lg transition-all"
            >
              Giriş Yap
            </a>
          </div>
        </div>
      </nav>
    </header>
  `,
  styles: []
})
export class HeaderComponent {
  isMobileMenuOpen = false;

  navigation: NavItem[] = [
    { name: 'Çalışanlar', path: '/employees' },
    { name: 'İzin Talepleri', path: '/leaves' },
  ];

  toggleMobileMenu() {
    this.isMobileMenuOpen = !this.isMobileMenuOpen;
  }
}
